version: "3.8"
services:
  movies:
    image: sahilnakade17/movies
    ports:
      - 91:80
    deploy:
      replicas: 3
  train:
    image: sahilnakade17/train
    ports:
      - 92:80
    deploy:
      replicas: 3
  recharge:
    image: sahilnakade17/recharge
    ports:
      - 93:80
    deploy:
      replicas: 3
  dth:
    image: sahilnakade17/dth
    ports:
      - 94:80
    deploy:
      replicas: 3
~
~
